import "@/styles/globals.css";

import { type Metadata } from "next";
import { GeistSans } from "geist/font/sans";

import { LoginButton } from "@/app/components/login-button";
import { LogoutButton } from "@/app/components/logout-button";
import { getServerAuthSession } from "@/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <nav className="flex h-[100px] justify-end p-8">
          {!session ? <LoginButton /> : <LogoutButton />}
        </nav>
        <main className="flex min-h-screen flex-col items-center justify-center">{children}</main>
      </body>
    </html>
  );
}
