name: Prisma DB Push on Main

on:
  push:
    branches:
      - main

jobs:
  prisma-db-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Prisma db:push
        run: pnpm db:migrate
        env:
          PLANETSCALE_HOST: ${{ secrets.PLANETSCALE_HOST }}
          PLANETSCALE_PASSWORD: ${{ secrets.PLANETSCALE_PASSWORD }}
          PLANETSCALE_USERNAME: ${{ secrets.PLANETSCALE_USERNAME }}
